name: pay_flow_app
description: PayFlow — demo app لتوضيح Clean Architecture + BLoC/Cubit في مشروع feature-first.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Networking
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Dependency Injection
  get_it: ^7.6.7

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # Device features
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
